### PR TITLE
Angular 9

### PR DESCRIPTION
**Pull request by philipjbrowning**

### CODE REVIEW

**Comment by Marcelh1983** [comment]
Hi @philipjbrowning ,

Thanks for the PR. I was working on a new version myself as well but stop because I don't use the package right now and didn't know other people do. I'll try to continue what I started and will merge your changes. Thanks again!

**Comment by philipjbrowning** [comment]
We were about to make one, upgrading Microsoft's library, but you already made it.

**Comment by Marcelh1983** [comment]
I created a 1.1.0-beta.0 version. Where I upgraded msal to the latest version and upgraded Angular. If you try this package, please let me know if it works for you. If so I'll publish it as the latest version. Thanks again.

**Comment by philipjbrowning** [comment]
@Marcelh1983 Going to look at it starting tonight

**Pull request merged**
